/** FO §7: huidige uitgangsconfiguratie, niet hardcoded in de planner. */

export const CONDITION_TYPES = [
  { id: 'ALWAYS', label: 'Altijd' },
  { id: 'HOME_MATCH', label: 'Bij thuiswedstrijd' },
  { id: 'HOME_MATCH_TEAM', label: 'Bij thuiswedstrijd van een team' },
  { id: 'ACTIVITY', label: 'Bij een activiteit' },
  { id: 'MANUAL', label: 'Alleen handmatig' },
];

export const CONDITION_TYPE_IDS = CONDITION_TYPES.map((c) => c.id);

export const ACTIVITY_TYPES = [
  { id: 'klaverjas', label: 'Klaverjasavond' },
  { id: 'toernooi', label: 'Toernooi' },
  { id: 'feest', label: 'Feestavond' },
  { id: 'ledenavond', label: 'Ledenavond' },
  { id: 'opening', label: 'Bijzondere opening' },
  { id: 'overig', label: 'Overig' },
];

export function defaultServiceRuleSeed() {
  return [
    {
      name: 'Dinsdag bar',
      weekday: 2,
      startTime: '19:00',
      endTime: '22:00',
      type: 'BAR',
      required: 1,
      slot: 'EVENING',
      conditionType: 'ALWAYS',
      sortOrder: 10,
    },
    {
      name: 'Woensdag bar',
      weekday: 3,
      startTime: '18:30',
      endTime: '22:00',
      type: 'BAR',
      required: 1,
      slot: 'EVENING',
      conditionType: 'ALWAYS',
      sortOrder: 20,
    },
    {
      name: 'Donderdag bar',
      weekday: 4,
      startTime: '18:30',
      endTime: '00:00',
      type: 'BAR',
      required: 1,
      slot: 'EVENING',
      conditionType: 'ALWAYS',
      sortOrder: 30,
    },
    {
      name: 'Vrijdag bar (klaverjas)',
      weekday: 5,
      startTime: '18:30',
      endTime: '00:00',
      type: 'BAR',
      required: 2,
      slot: 'EVENING',
      conditionType: 'ACTIVITY',
      conditionActivityType: 'klaverjas',
      sortOrder: 40,
    },
    {
      name: 'Zaterdag bar ochtend',
      weekday: 6,
      startTime: '07:30',
      endTime: '12:00',
      type: 'BAR',
      required: 3,
      slot: 'MORNING',
      conditionType: 'ALWAYS',
      teamDuty: true,
      teamDutySlotRole: 'MORNING',
      teamDutyReserved: 2,
      teamDutyAgeFrom: 8,
      teamDutyAgeTo: 12,
      sortOrder: 50,
    },
    {
      name: 'Zaterdag bar tweede shift',
      weekday: 6,
      startTime: '12:00',
      endTime: '16:30',
      type: 'BAR',
      required: 3,
      slot: 'AFTERNOON',
      conditionType: 'ALWAYS',
      teamDuty: true,
      teamDutySlotRole: 'SECOND',
      teamDutyReserved: 2,
      teamDutyAgeFrom: 13,
      teamDutyAgeTo: 17,
      sortOrder: 60,
    },
    {
      name: 'Zaterdag bar laatste shift',
      weekday: 6,
      startTime: '16:30',
      endTime: '19:30',
      type: 'BAR',
      required: 2,
      slot: 'EVENING',
      conditionType: 'ALWAYS',
      teamDuty: true,
      teamDutySlotRole: 'LAST',
      teamDutyReserved: 1,
      teamDutyAgeFrom: 13,
      teamDutyAgeTo: 17,
      sortOrder: 70,
    },
    {
      name: 'Zaterdag keuken ochtend',
      weekday: 6,
      startTime: '10:00',
      endTime: '13:00',
      type: 'KITCHEN',
      required: 1,
      slot: 'MORNING',
      conditionType: 'ALWAYS',
      sortOrder: 80,
    },
    {
      name: 'Zaterdag keuken middag',
      weekday: 6,
      startTime: '13:00',
      endTime: '16:00',
      type: 'KITCHEN',
      required: 2,
      slot: 'AFTERNOON',
      conditionType: 'ALWAYS',
      sortOrder: 90,
    },
    {
      name: 'Zaterdag keuken laat (Lekkerkerk 1 thuis)',
      weekday: 6,
      startTime: '16:00',
      endTime: '19:00',
      type: 'KITCHEN',
      required: 2,
      slot: 'EVENING',
      conditionType: 'HOME_MATCH_TEAM',
      conditionTeamName: 'Lekkerkerk 1',
      sortOrder: 100,
    },
    {
      name: 'Zondag bar ochtend',
      weekday: 0,
      startTime: '09:00',
      endTime: '13:00',
      type: 'BAR',
      required: 1,
      slot: 'MORNING',
      conditionType: 'ALWAYS',
      sortOrder: 110,
    },
    {
      name: 'Zondag bar middag',
      weekday: 0,
      startTime: '13:00',
      endTime: '16:00',
      type: 'BAR',
      required: 1,
      slot: 'AFTERNOON',
      conditionType: 'ALWAYS',
      sortOrder: 120,
    },
    {
      name: 'Zondag keuken',
      weekday: 0,
      startTime: '12:00',
      endTime: '15:00',
      type: 'KITCHEN',
      required: 1,
      slot: 'AFTERNOON',
      conditionType: 'ALWAYS',
      sortOrder: 130,
    },
  ];
}
